### ISSUE TITLE
Unrecognized non-utf-8 encoding

### ISSUE THREAD

**Issue by GavinQin** [Mobbeel/fataar-gradle-plugin#11]
when the string.xml contains chinese characters, in the aar ,it's show "????"

**Comment by oscarcpozas** [comment]
I assign myself to review this issue

**Comment by aveth** [comment]
Is there any update on this issue? I'm currently experiencing something that might be related. When building my app, I am seeing an error:

`79 actionable tasks: 79 executed

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':flutter:copyReleaseDependencies'.
> R.txt cannot generate

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 18s
`

Any updated would be very helpful. I'm trying to build an AAR from a Flutter module and using the following instructions: https://github.com/flutter/flutter/issues/23944

Thanks!

**Comment by oscarcpozas** [comment]
I tried to reproduce with the latest version of plugin (2.0.3) and Gradle plugin 3.1.4, and the characters are generated correctly: 
![screenshot 2019-01-10 at 13 23 55](https://user-images.githubusercontent.com/3399621/50968339-03767900-14db-11e9-8476-75439f668131.png)

**Comment by BigggFish** [comment]
in the aar, values.xml is in GBK format. When you open values.xml in UTF-8 format, it will show "???".
but my project is in UTF-8 format.

**Comment by BigggFish** [comment]
I found the reason.Because my operating system is Windows 10.So when generating new values.xml, the default format is GBK. Modify the default format to UTF-8, which can be solved.
ps:I'm not good at English.If you are not sure, please let me know.

**Comment by oscarcpozas** [comment]
So, this issue is solved?

**Comment by BigggFish** [comment]
yes! this issue is solved

**Comment by msrlin** [comment]
> yes! this issue is solved

我这边修改了默认UTF编码，打包出来的aar文件还是出现了BGK的乱码....你是怎么完全解决这个问题的

**Comment by msrlin** [comment]
> So, this issue is solved?

can you add a config to set encoding? sometime , we do not want to change our default pc setting. On the other hand,i changed my default encoding system, it still doesn't work, and there may be some unknown problems
